### PR TITLE
Last Updated timestamp in local timezone. Fixes #4 .

### LINKED ISSUE #4: Adapt "last updated" timestamp to show time in the visitor's timezone

### PR DESCRIPTION
**Pull request by bageshwar**

### CODE REVIEW

**Review by sudevschiz — COMMENTED** [review]
Thanks for the PR. Does this show the local timezones identifier? 
Like

`March 17, 2020 at 10:11 pm EST` 

If not, it could be confusing for the user.

**Comment by bageshwar** [comment]
> Thanks for the PR. Does this show the local timezones identifier?
> Like
> 
> `March 17, 2020 at 10:11 pm EST`
> 
> If not, it could be confusing for the user.

The date is displayed as `Tue Mar 17 2020 18:41:00 GMT+0200 (Jerusalem Standard Time)` .

**Comment by triedcatched** [comment]
It can also be like last updated: xx minutes ago

**Comment by bageshwar** [comment]
> It can also be like last updated: xx minutes ago

Sure, that actually, would be more helpful.

**Comment by bageshwar** [comment]
@triedcatched , @sudevschiz Is it ok to introduce another JS library. I am evaluating [momentjs](https://momentjs.com/) with a footprint of 16kb, available over cdn.

**Comment by triedcatched** [comment]
Let's see if we can do this from sheets itself. Then we can ditch the update on source html

**Comment by bageshwar** [comment]
> Let's see if we can do this from sheets itself. The we can ditch the update on source html

sure.

**Comment by triedcatched** [comment]
> 
> 
> @triedcatched , @sudevschiz Is it ok to introduce another JS library. I am evaluating [momentjs](https://momentjs.com/) with a footprint of 16kb, available over cdn.

It's okay to add momentjs.

maybe it might be difficult to add the "xx minutes ago" in the sheets. Could you see if you can do it from the javascript and submit again?

**Comment by JunaidBabu** [comment]
Any updates on showing last updated as "xx minutes ago" ?

**Review by JunaidBabu — APPROVED** [review]

**Comment by bageshwar** [comment]
> Any updates on showing last updated as "xx minutes ago" ?

This is taken care now. Looks as below
image

**Comment by sudevschiz** [comment]
`docs` folder updated?

**Comment by triedcatched** [comment]
> `docs` folder updated?

No I'll do it.


This looks good

**Pull request merged**
